[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
matic = "${MATIC_RPC_URL}"

[etherscan]
matic = { key = "MATICSCAN_API_KEY" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config